Early iterator closing in dispatch
authzed/spicedb pull request #1016
Opened 2022-11-26 01:36 UTC by josephschorr

Add a lint check and fix usages of iterators to ensure they are closed as early as we can

2022-11-26 10:36 UTC, vroldanbet requested changes
Why is the analyzers binary being checked in?

2022-11-26 18:59 UTC, josephschorr commented
> Why is the analyzers binary being checked in?

Must have accidentally added it. Removed

2022-11-28 13:52 UTC, vroldanbet reviewed
👋🏻 I fail to see how this help with DB connection connection, maybe I'm missing something. The only implementation of a relationship iterator used by production code is `sliceRelationshipIterator`, which does not hold any references to database connections or any state that would cause DB conns to be released.

2022-11-28 13:52 UTC, vroldanbet commented on tools/analyzers/closeafterusagecheck/closeafterusagecheck_test.go
> +	analyzer.Flags.Set("must-be-closed-after-usage-types", "*notimmediatelyclosed.SomeIterator")
unhandled error

2022-11-28 17:37 UTC, vroldanbet approved these changes
👍🏻 looks good to me

2022-11-28 17:41 UTC, merged