doc: add information on when `insecure` is okay to the crdb readme
authzed/spicedb pull request #1251
Opened 2023-04-06 18:53 UTC by ecordell

2023-04-10 12:58 UTC, vroldanbet reviewed
LGTM, left some nits and questions. I think I'd be worth adding this also to https://authzed.com/docs/spicedb/selecting-a-datastore#cockroachdb

2023-04-10 12:58 UTC, vroldanbet commented on internal/datastore/crdb/README.md
> +### Application Mitigations for Misapplying Old ACLs
nit: may be better to make this a subsection of `Mis-apply Old ACLs to New Content`

```suggestion
#### Application Mitigations for Misapplying Old ACLs
```

2023-04-10 16:15 UTC, josephschorr commented on internal/datastore/crdb/README.md
> +- **Clock skew**. A larger clock skew gives a bigger window in which timestamps can be reversed. But note that CRDB enforces a max offset between clocks, and getting within some fraction of that max
"boot" -> "kick"

2023-04-10 19:05 UTC, ecordell commented on internal/datastore/crdb/README.md
> +- And the writes touch disjoint sets of relationships
Nope, if the the writes land in the same ranges (which they would if any relationships overlap) then the timestamps will get synchronized

2023-04-11 18:47 UTC, jakedt requested changes
You might also want to address the fact that timestamp reversals on disjoint graphs (not just non-overlapping) will never result in the new enemy problem. Maybe write up some examples on when there wouldn't be any impact whatsoever.

2023-04-12 18:58 UTC, ecordell commented
@jakedt updated with examples like you suggested

2023-04-12 21:15 UTC, jakedt approved these changes

2023-04-14 01:06 UTC, ecordell commented
@jakedt fixed

2023-05-05 18:11 UTC, jakedt approved these changes

2023-05-05 18:17 UTC, merged