Reconnect logging and tracing into the disconnect LR/RR context
authzed/spicedb pull request #1408
Opened 2023-06-26 18:11 UTC by josephschorr

2023-06-26 18:26 UTC, jakedt requested changes

2023-06-26 18:26 UTC, jakedt commented on internal/graph/context.go
>  // Also returns a function for canceling the newly context, without canceling the parent context.
newly created

2023-06-26 18:26 UTC, jakedt commented on internal/graph/context.go
>  // This is used when cancelation of a child context should not propagate upwards.
Context cancellation never propagates upwards.

2023-06-26 18:34 UTC, josephschorr commented on internal/graph/context.go
>  // This is used when cancelation of a child context should not propagate upwards.
Removed

2023-06-28 15:40 UTC, jakedt approved these changes

2023-06-28 17:20 UTC, merged