Add server version middleware to serve-testing
authzed/spicedb pull request #2006
Opened 2024-07-30 21:30 UTC by josephschorr

Fixes #2003

2024-07-31 09:00 UTC, vroldanbet requested changes
Can you reuse the defaults here [instead](https://github.com/authzed/spicedb/blob/f30c5cb2f2eb043da2d0fa511ab74d758636c9e4/pkg/cmd/server/defaults.go#L214)? That way we won't have drifting in the future. It also uses the middleware framework, which is more robust when it comes to dependencies between middlewares.

2024-07-31 14:23 UTC, josephschorr commented
> Can you reuse the defaults here [instead](https://github.com/authzed/spicedb/blob/f30c5cb2f2eb043da2d0fa511ab74d758636c9e4/pkg/cmd/server/defaults.go#L214)? That way we won't have drifting in the future. It also uses the middleware framework, which is more robust when it comes to dependencies between middlewares.

`serve-testing` doesn't use most of those defaults and we've have to replace a few of them. I suppose we could inject/override some, but that has its own risks

2024-08-01 18:09 UTC, josephschorr commented
Updated to use the middleware system as we discussed

2024-08-05 14:32 UTC, ecordell commented on pkg/cmd/server/defaults.go
> +	Logger                  zerolog.Logger      `debugmap:"hidden"`
Why are all of these exported now? I don't see that being used anywhere.

2024-08-05 16:33 UTC, ecordell approved these changes

2024-08-05 18:46 UTC, merged