WIP: simplify datastore construction
authzed/spicedb pull request #317
Opened 2021-12-02 22:38 UTC by ecordell

Currently just a sketch of an option for refactoring.

2021-12-07 21:04 UTC, jzelinskie requested changes

2021-12-07 21:10 UTC, ecordell commented on internal/datastore/datastore.go
> +	//  ReverseQueryTuplesFromSubjectNamespace creates a builder for reading
I don't know how this happened...

2021-12-07 21:22 UTC, jzelinskie submitted a review, later dismissed

2021-12-08 18:06 UTC, jzelinskie approved these changes

2021-12-08 18:06 UTC, merged