Ensure preconditions on tuple writes in Postgres honor deletions
authzed/spicedb pull request #547
Opened 2022-04-20 19:06 UTC by josephschorr

Fixes #339

2022-04-20 21:46 UTC, vroldanbet submitted a review, later dismissed
Changes to mysql datastore LGTM

2022-04-20 21:57 UTC, jakedt requested changes

2022-04-20 21:57 UTC, jakedt commented on internal/datastore/postgres/tuple.go
> +	query = query.Where(sq.Eq{colDeletedTxn: liveDeletedTxnID})
The caller of this method should use `filterToLivingObjects`.

2022-04-20 21:57 UTC, jakedt commented on internal/datastore/mysql/tuple.go
> +	query = query.Where(sq.Eq{colDeletedTxn: liveDeletedTxnID})
The caller of this method should use `filterToLivingObjects`.

2022-05-05 15:28 UTC, josephschorr commented
Closed in favor of #581

2022-05-05 15:28 UTC, closed without merging